version: '3'
services:
    engine:
        container_name: engine
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8080:8080
        volumes:
            - ./:/app